### ISSUE TITLE
Transformation_review.py error

### ISSUE THREAD

**Issue by trmchale1** [cisc3620/review#23]
First:
python3 transformation_review.py

Second: I receive output from the program:

Enter 'p' for picture, 'r' for rotation, 's' for scale, 'c' for combo, 't' for translation, a number n for an n-item quiz, 'review' to save a pdf quiz, or nothing to quit, and press enter 

Third: I enter 'p' for picture

I get the below error

Traceback (most recent call last):
  File "/root/3620/review/review.py", line 260, in getq
    x = numpy.random.randint(len(qtypes), size=int(q))	
ValueError: invalid literal for int() with base 10: 'p'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "transformation_review.py", line 133, in <module>
    rv.main(tqtypes)
  File "/root/3620/review/review.py", line 277, in main
    getq(q, qtypes)
  File "/root/3620/review/review.py", line 265, in getq
    qtypes[q][0]()
  File "transformation_review.py", line 115, in pictureq
    call(["Rscript", "Rcode/generate_figs.R", transformation[1]] + [str(p) for p in params])
  File "/usr/lib/python3.4/subprocess.py", line 537, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'Rscript'

**Comment by rivlev** [comment]
It looks like R is not installed, please see the Readme for installation instructions. It is only required for the picture questions in the transformation review.

**Comment by trmchale1** [comment]
Understood, my apologies professor.
